In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
os.getcwd()


'/content'

In [3]:
!ls

drive  sample_data


In [5]:
#this is the dataset location which is shown in video
'''
os.chdir('/content/drive/My Drive/ANN')
'''
#now you have to use below one as you already created Data folder shortcut in My Drive
os.chdir('/content/drive/My Drive/day2/')


In [6]:
os.getcwd()

'/content/drive/My Drive/day2'

In [7]:
!ls

Churn_Modelling.csv  Day_2.py  DL_Intro_ANN_Churn_Modeling.ipynb


In [8]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

In [9]:
dataset.shape


(10000, 14)

In [10]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [11]:
dataset.shape

(10000, 14)

In [12]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values

In [15]:
type(features)

numpy.ndarray

In [16]:
features.shape

(10000, 10)

In [17]:
features[0:10,:]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [18]:
dataset.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [19]:
features


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
labels

array([1, 0, 1, ..., 1, 1, 0])

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

features = np.array(columnTransformer.fit_transform(features), dtype = np.float32)



In [22]:
features[0:10,:]


array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.1900000e+02, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.0800000e+02, 4.1000000e+01, 1.0000000e+00,
        8.3807859e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.0200000e+02, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.9900000e+02, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826633e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+0

In [23]:

features = features[:, 1:] #drop the first dummy column for Geography


In [24]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
      dtype=float32)

In [25]:

features = features[:, [0,1,3,4,5,6,7,8,9,10,11]] #drop the column for Gender


In [26]:
features.shape

(10000, 11)

In [27]:
features[0,:]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [28]:
features.shape

(10000, 11)

In [29]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [30]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [32]:
features_train[0]

array([-0.56984437,  1.7430905 , -1.0916871 ,  0.16958177, -0.46460798,
        0.00666099, -1.2157176 ,  0.8095029 ,  0.64259493, -1.0322704 ,
        1.1064317 ], dtype=float32)

In [33]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [34]:
classifier = Sequential()

In [35]:
features.shape

(10000, 11)

In [36]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [37]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation='sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

Epoch 1/10
800/800 [==============================] - 5s 2ms/step - loss: 0.4908 - accuracy: 0.7955
Epoch 2/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4270 - accuracy: 0.7960
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4193 - accuracy: 0.8179
Epoch 4/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4132 - accuracy: 0.8306
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4094 - accuracy: 0.8316
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4066 - accuracy: 0.8339
Epoch 7/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4047 - accuracy: 0.8331
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4028 - accuracy: 0.8349
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4018 - accuracy: 0.8340
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4009 - accuracy: 0.8365

In [54]:
#labels_pred = classifier.predict_classes(features_test)

model = Sequential()
labels_pred =np.argmax(model.predict(features_test), axis=-1)
#labels_pred =model.predict(features_test) 
#labels_pred = (labels_pred > 0.5)

In [55]:
labels_pred

array([0, 8, 1, ..., 1, 0, 0])

In [56]:
len(labels_pred)

2000

In [57]:
list(zip(labels_test, labels_pred))

[(0, 0),
 (1, 8),
 (0, 1),
 (0, 3),
 (0, 0),
 (1, 1),
 (0, 1),
 (0, 1),
 (1, 4),
 (1, 4),
 (0, 5),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (1, 0),
 (0, 5),
 (0, 4),
 (0, 10),
 (0, 9),
 (0, 0),
 (0, 3),
 (0, 1),
 (0, 6),
 (0, 3),
 (0, 3),
 (0, 1),
 (0, 0),
 (0, 10),
 (0, 3),
 (0, 9),
 (1, 4),
 (0, 5),
 (0, 4),
 (0, 3),
 (0, 0),
 (0, 3),
 (0, 3),
 (0, 1),
 (0, 10),
 (0, 6),
 (1, 1),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 9),
 (0, 1),
 (0, 5),
 (0, 10),
 (0, 3),
 (1, 7),
 (0, 1),
 (0, 9),
 (0, 4),
 (0, 4),
 (0, 1),
 (0, 0),
 (0, 1),
 (1, 10),
 (1, 8),
 (0, 0),
 (0, 1),
 (0, 1),
 (1, 6),
 (1, 3),
 (1, 10),
 (0, 2),
 (0, 10),
 (0, 0),
 (1, 0),
 (0, 4),
 (0, 1),
 (0, 9),
 (1, 4),
 (1, 1),
 (0, 0),
 (1, 4),
 (0, 9),
 (0, 7),
 (0, 9),
 (1, 0),
 (1, 4),
 (0, 6),
 (0, 1),
 (1, 4),
 (0, 4),
 (0, 9),
 (0, 5),
 (1, 7),
 (0, 10),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 7),
 (0, 9),
 (1, 4),
 (0, 7),
 (0, 3),
 (0, 1),
 (0, 0),
 (0, 2),
 (0, 0),
 (0, 2),
 (0, 10),
 (0, 1),
 (0, 6),
 (0, 0),
 (1, 5),
 (0, 10),
 (0, 6),


In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

In [59]:
cm


array([[335, 380,  75, 127, 116, 144,  91,  42,   6, 150, 129],
       [125,  49,  10,  24,  66,  21,  20,  58,   4,   9,  19],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])